services:
  db:
    container_name: pumptrack-db
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-password}
      - POSTGRES_USER=${POSTGRES_USER-user}
    ports:
      - ${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
